### ISSUE TITLE
方向键上下切换选中位置

### ISSUE THREAD

**Issue by chenyong** [jimengio/doc-frame#5]
这里的侧边栏 http://fe.jimu.io/doc-frame/#/doc-block

现在侧边栏当中支持回车键选中第一项 https://github.com/jimengio/doc-frame/blob/master/src/doc-sidebar.tsx#L38 . 需要支持方向键上下切换选中项.

注意有搜索的情况, 需要切换时能根据搜索结果做正确的跳转.

**Comment by arieslx** [comment]
已完成

**Comment by chenyong** [comment]
Related https://github.com/jimengio/doc-frame/pull/9
